version: '3.8'
services:
  app:
    image: "stole-token-sharp-dev-net-app"
    container_name: "my_terminal"
    user: "testuser"
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '27014:7681'
    command: "ttyd -c testuser:qwer1234 -t rendererType=dom python3 terminal.py"
