version: '3.8'
services:
  app:
    image: 'my_terminal'
    container_name: 'my_terminal'
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '27014:7681'
