version: '3.8'
services:
  app:
    container_name: 'my_terminal'
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    user: testuser
    ports:
      - '27014:7681'
    volumes:
      - ./userspace/:/app/userspace/
    command: "ttyd -c testuser:qwer1234 -t rendererType=dom python3 terminal.py"
