version: '3.8'
services:
  app:
    container_name: 'my_stage_terminal' # todo: change to my_terminal when you will merge it
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    user: testuser
    ports:
      - '27015:7681'  # todo: change to 27014 when will merge to master
    volumes:
      - userspace/:/app/userspace/
    command: "ttyd -c testuser:qwer1234 -t rendererType=dom python3 terminal.py"
